// THIS FILE IS AUTOGENERATED
// ANY ATTEMPTS TO CHANGE IT WILL RESULT IN IT BEING REVERTED
node {
    stage('SCM Clone') {
        checkout scm
    }

    stage('Maven Build') {
        def verb = env.BRANCH_NAME == 'master' ? 'deploy' : 'package'
        sh "${tool 'Maven 3'}/bin/mvn clean ${verb} -B -U"
    }
}